fail_fast: false
repos:
  - repo: local
    hooks:
      - id: lib-dir-test
        name: Test ensure4j
        entry: cmd.exe /c mvnw.cmd
        args: [ "-f", "lib/pom.xml", "clean", "test" ]
        language: system
        files: ^lib/src
        require_serial: true
        pass_filenames: false