fail_fast: false
repos:
  - repo: local
    hooks:
      - id: ensure-test
        name: Ensure pre commit test
        entry: cmd.exe /c mvnw.cmd
        args: [ "-f", "ensure/pom.xml", "clean", "test" ]
        language: system
        files: ^ensure/src
        require_serial: true
        pass_filenames: false